name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - run: npm ci
      - if: github.event_name == 'push'
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          COMMIT_HASH=$(git rev-parse --short HEAD)
          NEW_VERSION="$CURRENT_VERSION-$COMMIT_HASH"
          npm version $NEW_VERSION --no-git-tag-version
          npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: github.event_name == 'release'
        run: npm publish --tag stable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
